{{- if .Values.controller.enabled }}
{{- if or (not .Values.controller.serviceAccount) (default true .Values.controller.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zen-lock.controllerServiceAccountName" . }}
  namespace: {{ include "zen-lock.namespace" . }}
  labels:
    {{- include "zen-lock.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if and .Values.controller.serviceAccount .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

