# Copyright 2025 Kube-ZEN Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.webhook.enabled }}
{{- if .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "zen-lock.fullname" . }}-webhook-cert
  namespace: {{ include "zen-lock.namespace" . }}
spec:
  issuerRef:
    name: {{ .Values.webhook.certManager.issuer.name }}
    kind: {{ .Values.webhook.certManager.issuer.kind }}
  secretName: {{ .Values.webhook.certSecret }}
  dnsNames:
    - {{ include "zen-lock.fullname" . }}-webhook.{{ include "zen-lock.namespace" . }}.svc
    - {{ include "zen-lock.fullname" . }}-webhook.{{ include "zen-lock.namespace" . }}.svc.cluster.local
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "zen-lock.fullname" . }}-mutating-webhook
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "zen-lock.namespace" . }}/{{ include "zen-lock.fullname" . }}-webhook-cert
  {{- end }}
  labels:
    {{- include "zen-lock.labels" . | nindent 4 }}
webhooks:
  - name: mutate-pods.zen-lock.security.kube-zen.io
    clientConfig:
      service:
        name: {{ include "zen-lock.fullname" . }}-webhook
        namespace: {{ include "zen-lock.namespace" . }}
        path: "/mutate-pods"
      {{- if not .Values.webhook.certManager.enabled }}
      # caBundle must be set manually if cert-manager is disabled
      # caBundle: <base64-encoded-ca-certificate>
      {{- end }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: NoneOnDryRun
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 10 }}
    namespaceSelector:
      matchLabels:
        zen-lock: enabled
{{- end }}

