{{- if .Values.webhook.enabled }}
{{- if or (not .Values.webhook.serviceAccount) (default true .Values.webhook.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zen-lock.webhookServiceAccountName" . }}
  namespace: {{ include "zen-lock.namespace" . }}
  labels:
    {{- include "zen-lock.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  {{- if and .Values.webhook.serviceAccount .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.webhook.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

